### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Botspot** [Nunya-9018/usb-boot-retro-pi#1]
Hello, why have you invited me to collaborate on this repository?

**Comment by Nunya-9018** [comment]
So you could help me if I need help btw I'm homers rebuttal

**Comment by Nunya-9018** [comment]
Also your helping me with the usb to .img thing

**Comment by Botspot** [comment]
> So you could help me if I need help btw I'm homers rebuttal

Sure I can try.

> Also your helping me with the usb to .img thing

Yes I am.
